### ISSUE TITLE
Adding About Us page to the Website

### ISSUE THREAD

**Issue by pooranjoyb** [arnab2001/Coinverse#103]
## Description

I would like to add an `About Us` Page to the website
It is important because,
- The `About` page fosters familiarity and trust. 
- The `About` page helps visitors understand their options. 
- The `About` page humanizes your business.
- Tell your story on your `About` page.

## I would like to work on this issue under JWOC 2023. Please assign @arnab2001 😄

**Comment by arnab2001** [comment]
Sure go ahead , I'm assigning the issue to you
