### ISSUE TITLE
Design a logo for Converse

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#20]

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by sarkartanmay393** [comment]
I want to work on this issue. JWOC

**Comment by Awesomeasma** [comment]
I want to work on this issue under JWOC. I have creative skills to make the logo look fab. Please assign this issue to me.

**Comment by Priyamakeshwari** [comment]
I would like to work on this issue under JWOC.

**Comment by arnab2001** [comment]
Assigned @Awesomeasma to the issue , good luck

**Comment by Awesomeasma** [comment]
should I upload the screenshot of the logo, first ?

**Comment by Awesomeasma** [comment]
![logo-coinverse](https://user-images.githubusercontent.com/86073340/221107501-ed9e49c5-2b16-4805-9200-02db8ddf82f5.png)

@arnab2001  How is it ?

**Comment by arnab2001** [comment]
Great job , accepting your pr

**Comment by Awesomeasma** [comment]
Would u mind to elaborate what u mean ??

**Comment by eddybank** [comment]
> Would u mind to elaborate what u mean ??

I believe he means to update the Navbar where the stock logo sits currently. If you could post the image here, I can get it sorted for you.

**Comment by Awesomeasma** [comment]
@eddybank 
This is the image of the logo : 
![logo-coinverse](https://user-images.githubusercontent.com/86073340/221116109-f96c4358-1acc-4e34-82f7-d6931ccf7ec0.png)

**Comment by arnab2001** [comment]
@eddybank yes exactly I if he can do it then that would be great

**Comment by eddybank** [comment]
Removed the background

![image](https://user-images.githubusercontent.com/89403905/221121159-0eb08f7c-b5d0-4f2b-9730-c95c72e2235b.png)


It looks good but when sidebar is minimized the bottom text is very small and contrasts bad. 

![image](https://user-images.githubusercontent.com/89403905/221121218-4a55038c-f30a-4808-88f7-9ba4727a1581.png)

Would you happen to have this in a higher resolution, I think it would help?

**Comment by arnab2001** [comment]
Yah , it won't go well when the sidebar is minimised I didn't noticed that , also ofc it needs to be in higher resolution and without bg finally for integration.

**Comment by Awesomeasma** [comment]
@eddybank 
@arnab2001 

![coinverse-logo](https://user-images.githubusercontent.com/86073340/221167049-b016f52a-68c3-4aa0-8388-0dc30a52928f.jpg)

This is a better resolution image.. does it help ??

Please let me know if you want me to do any further modifications..

**Comment by Awesomeasma** [comment]
@eddybank 
@arnab2001 

Here's the high resolution version of the logo... does it help ??
Please let me know if u want me to make any modifications further ...

![coinverse-logo](https://user-images.githubusercontent.com/86073340/221168469-f8aee3e1-5d9c-4892-b71b-49553195d7cc.jpg)

**Comment by eddybank** [comment]
@arnab2001 I think a solution could be adding some logic in Navbar to switch the image whether the sider is collapsed or not. 


### Minimized
![image](https://user-images.githubusercontent.com/89403905/221502227-f1519908-846e-41ad-97cb-ff71d5c66ef7.png)

### Not-minimized
![image](https://user-images.githubusercontent.com/89403905/221502340-b3582dc9-14d8-4d86-90f0-2eb1de1acc59.png)

Basically swap image and add link when the sidebar is minimized.

**Comment by eddybank** [comment]
### Update from my previous comment

Took a look at the pull request open and saw their changes, so I updated my codebase and gonna work in the logo without any text because "Coinverse" is now at the top of the page.
