### ISSUE TITLE
beautify Global Crypto stats section 

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#21]

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by bcsamrudh** [comment]
@arnab2001 . I would like to contribute

**Comment by arnab2001** [comment]
sure, are you participating in JWOC? if so then you need to comment "I want to work on this issue under JWOC"

**Comment by bcsamrudh** [comment]
Yes under JWOC

**Comment by dibyendu02** [comment]
I want to work on this issue under JWOC

**Comment by arnab2001** [comment]
@dibyendu02 assigned the issue to you , you can work on it . Good luck 🤞

**Comment by vatan-prakash** [comment]
please assign this issue to me under JWOC

**Comment by arnab2001** [comment]
@vatan-prakash is assigned task to @dibyendu02 , if he is unable to complete by tomorrow then i will assign the issue to you
