### ISSUE TITLE
add option to bookmark coins  (save data in local storage)

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#22]

**Comment by eddybank** [comment]
Can you assign this to me?

**Comment by arnab2001** [comment]
Sure , assigning the issue to you

**Comment by eddybank** [comment]
## Update

Hey wanted to give an update on progress. 
1. Added a button on crypto details page to allow for bookmarking/un-bookmarking crypto pages. 

![image](https://user-images.githubusercontent.com/89403905/220810288-22100c19-4cfe-40d8-a867-bf0cb2215518.png)

2. Added a Submenu to the navbar to show the current Bookmarks. It re-renders when there is a change in bookmarks. 

![image](https://user-images.githubusercontent.com/89403905/220810473-99c03273-74fa-4d78-879f-5446df9ce512.png)

### To-do

As of right now, I need to add more details for the bookmark menu items--in the best case, both symbol and icon--although utilizing the API hooks as been challenging. In addition, I have to fix the styling for Menu for both of its states (long crypto names and when minimized the submenu doesn't show text).


To wrap it up, I should be able to close the issue by the weekend.

**Comment by eddybank** [comment]
I was able to get through the bugs and finished much faster than expected.

**Comment by arnab2001** [comment]
great job on the issue, it was really well-made feature. I was wondering if it's possible to add a "add to favorite option" from the crypto stats card itself

**Comment by eddybank** [comment]
@arnab2001 I will try to figure a way to do it. The main issue is that the cards themselves are 'links' so clicking on the bookmark icon with it being on the card will redirect to the detail page.
