### ISSUE TITLE
Improve design of the Footer/redesign the footer

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#23]

**Comment by Laxmankohar** [comment]
Hey @arnab2001 , I would like to work on this issue under JWOC. Can you please assign it to me?

**Comment by arnab2001** [comment]
@Laxmankohar assigned you the issue, good luck

**Comment by Rubyseher** [comment]
I am interested to fix this issue , I am participating under JWOC. Can you assign me this issue?

**Comment by Laxmankohar** [comment]
@arnab2001 , Please have a look.
![image](https://user-images.githubusercontent.com/73365025/220122084-56f6b0b5-f02f-4362-a8eb-f02351adce10.png)

**Comment by arnab2001** [comment]
@Laxmankohar Ok go ahead with the pr , good job :)
