### ISSUE TITLE
News Api 

### ISSUE THREAD

**Issue by JasonDsouza212** [arnab2001/Coinverse#29]
- The API that fetches News data seems to have some problem
- Its not loading

**Comment by arnab2001** [comment]
@JasonDsouza212 yes there is an issue with the Bing news search api , it has internal server error probably . If you want to fix it by implimenting other news api or any other way then that will be great

**Comment by eddybank** [comment]
Apparently Bing APIs have been down, even for paid subscriptions, so will likely have to wait to switch APIs.

**Comment by JasonDsouza212** [comment]
I think they have changed the API endpoints or they might be thinking about changing it

**Comment by TuhinBanerjee31** [comment]
Can I get assigned to this issue under JWOC?

**Comment by arnab2001** [comment]
Yes , I'm assigning it to you @arnab2001

**Comment by SHAIKASIFALI** [comment]
can i work on this issue
