### ISSUE TITLE
[OPEN][UPDATE]: Stick Navbar And Sidebar both

### ISSUE THREAD

**Issue by AbhiPatel10** [arnab2001/Coinverse#31]
We can stick navbar and sidebar so that will be a more user friendly.

https://user-images.githubusercontent.com/76242769/221000829-e5a8a03f-bc8e-4c55-a7e8-c980887190c2.mp4

Assign this issue to me under JWOC. 

Thank you 🤝

**Comment by arnab2001** [comment]
I assigned the issue to you @AbhiPatel10 , you can work on it 
Good luck

**Comment by AbhiPatel10** [comment]
Thank you for assigning too fast 🤝

**Comment by arnab2001** [comment]
have you done working on it ?

**Comment by Laxmankohar** [comment]
Hey @arnab2001 , i want to work on this issue under JWOC. Can you please assign it to me?

**Comment by AbhiPatel10** [comment]
I'm getting this error

![image](https://user-images.githubusercontent.com/76242769/222905894-2411266b-c59e-412a-b3fb-d73e34adc52e.png)

**Comment by Awesomeasma** [comment]
@arnab2001 
I would like to work on this under JWOC.

**Comment by arnab2001** [comment]
> I'm getting this error
> 
> ![image](https://user-images.githubusercontent.com/76242769/222905894-2411266b-c59e-412a-b3fb-d73e34adc52e.png)
> 

@AbhiPatel10 You need add a .env file , open rapid api , search coinranking api , subscribe to the api , take api key and put it in the api key field (check .envDEMO file )

**Comment by arnab2001** [comment]
@Laxmankohar I'm assigning you the issue , good luck

**Comment by AbhiPatel10** [comment]
> > I'm getting this error
> > ![image](https://user-images.githubusercontent.com/76242769/222905894-2411266b-c59e-412a-b3fb-d73e34adc52e.png)
> 
> @AbhiPatel10 You need add a .env file , open rapid api , search coinranking api , subscribe to the api , take api key and put it in the api key field (check .envDEMO file )

Yes I added .env file but Not able to solve this error

**Comment by ManasaKaza** [comment]
I would like to work on this issue under JWOC
