### ISSUE TITLE
Adding zoom effect (on hover) on the coin cards of "top 10 cryptocurrencies of the world"

### ISSUE THREAD

**Issue by deepbeatz** [arnab2001/Coinverse#32]

**Comment by deepbeatz** [comment]
@arnab2001 plz assign me this issue under jwoc 2k23

**Comment by deepbeatz** [comment]
https://user-images.githubusercontent.com/79015311/221130429-8d7f6197-f367-4a79-9c4e-f056d8ad56d8.mp4

@arnab2001 shall i create pr?? but before that plz assign me and give the appropriate labels.....

**Comment by arnab2001** [comment]
Sure , great job

**Comment by arnab2001** [comment]
Assigned you the issue with proper lable

**Comment by deepbeatz** [comment]
pr sent

**Comment by deepbeatz** [comment]
new pr sent
