### ISSUE TITLE
favicon is not visible

### ISSUE THREAD

**Issue by abhijain2003** [arnab2001/Coinverse#35]
I don't know if favicon is there or not, but it is not visible to end-user, it might be because of light color or small size.

I want to work on this

**Comment by arnab2001** [comment]
Sure , go ahead with the issue I'm assigning it to you

**Comment by abhijain2003** [comment]
sure I am working

**Comment by abhijain2003** [comment]
raised pr 

https://github.com/arnab2001/Coinverse/pull/41
