### ISSUE TITLE
enhancing UI of home page and nav-bar and side-bar

### ISSUE THREAD

**Issue by deepbeatz** [arnab2001/Coinverse#36]

**Comment by deepbeatz** [comment]
@arnab2001 assign me this issue under JWOC

**Comment by arnab2001** [comment]
@deepbeatz Assigned you to the issue

**Comment by deepbeatz** [comment]
pr sent

**Comment by deepbeatz** [comment]
did all this:
1. cool animated coinverse head title (responsive)
2. coinverse logo zoom effect on hover
3. added link of the coinverse website in the coinverse text below coinverse logo
4. logo zoom effect and light shadow on hover on the 5 subtitles of the global crypto stats
5. bulb icon hover zoom effect (and color change to yellow on hover in dark mode cuz it looks good)
6. "show more" text was black in dark mode and so wasnt visible, so fixed that too

**Comment by Code1705** [comment]
I want to contribute to this issue by making changes in the css file to look attractive and pleasing , please assign this issue to me under JWOC.
