### ISSUE TITLE
Improving the UI

### ISSUE THREAD

**Issue by SakshiShah29** [arnab2001/Coinverse#49]
Redesigning of the search bar and the cards needed.
I would like to work on this issue.

Please assign it to me.

**Comment by arnab2001** [comment]
sure, go ahead. I have assigned you the issue

**Comment by Code1705** [comment]
I would like to contribute to this issue , kindly assign me under jwoc .

**Comment by SakshiShah29** [comment]
@arnab2001 I completed the redesigning of the search bar but due to errors with the get request with the apis I cant see the cards. Can you assist me as to hoe to resolve this error?
