### ISSUE TITLE
Mobile Responsive- fix footer for mobile view

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#5]

**Comment by sajdakabir** [comment]
Hey @arnab2001 , can you assigne it to me?

**Comment by arnab2001** [comment]
I assigned you to the issue , you can work on it 👍

**Comment by ManasaKaza** [comment]
I want to work on this issue under JWOC

**Comment by sandeeprawat28** [comment]
Please assign this issue to me

**Comment by arnab2001** [comment]
I assigned the issue @ManasaKaza, 
On  fcfs basis for jwoc . Good luck 🤞

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by ManasaKaza** [comment]
Hi @arnab2001 I don't know why I am not even able to open the project in my local host. Can you once tell me how to do that
