### ISSUE TITLE
Mobile Responsive- Fix "Global crypto stats" section for mobile view

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#6]

**Comment by sandeeprawat28** [comment]
Please assign this issue to me

**Comment by deepbeatz** [comment]
I want to work on this issue under JWOC

**Comment by arnab2001** [comment]
@deepbeatz i assigned the issue to you for jwoc, good luck

**Comment by deepbeatz** [comment]
Thanks sir , will get back to you as soon as I can

**Comment by sandeeprawat28** [comment]
I want to work on this issue under JWOC

**Comment by deepbeatz** [comment]
@arnab2001 sir i can see that u haven't assigned me the issue, i am already working on it.....can u please assign me?

**Comment by deepbeatz** [comment]
@arnab2001 sir?? waiting for you to assign me, waiting for your reply sir

**Comment by arnab2001** [comment]
@deepbeatz sorry my bad I assigned it to you

**Comment by deepbeatz** [comment]
Thanks sir , will get back to you asap

**Comment by deepbeatz** [comment]
<img width="960" alt="Screenshot 2023-02-20 12 26 08" src="https://user-images.githubusercontent.com/79015311/220034604-a7b34ff5-8229-42a0-bc6e-1a08b3345e93.png">
@arnab2001 sir can u please tell me where i need to make the changes, it looks responsive already ......please let me know how can i make this more responsive.
