### ISSUE TITLE
Fix: News cards in dark theme

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#60]
![image](https://user-images.githubusercontent.com/63441472/222927044-c4d1665a-16d0-40c0-a667-617f415bb3f9.png)

**Comment by TuhinBanerjee31** [comment]
I want to work on this issue under JWOC

**Comment by Laxmankohar** [comment]
hey @arnab2001 , i want to work on this issue under JWOC. Can you please assign it to me?

**Comment by arnab2001** [comment]
@TuhinBanerjee31 you can work on it

**Comment by ManasaKaza** [comment]
I would like to work on this issue under JWOC
