### ISSUE TITLE
Redesigning the crypto stats section

### ISSUE THREAD

**Issue by SakshiShah29** [arnab2001/Coinverse#65]
Redesigning of the crypto stats section can be done
adding more css attributes to the existing class and revamping the UI of the same
![image](https://user-images.githubusercontent.com/65860201/223061497-6868df39-6cce-49f8-a55a-e13edc28c24e.png)

Please assign this issue to me

**Comment by deepbeatz** [comment]
this issue is already taken care of @arnab2001

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by deepbeatz** [comment]
This has been taken care of in another issue 
@arnab2001
