### ISSUE TITLE
FIX: Sticky navbar and header

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#74]
make the navbar and header sticky (without breaking any existing feature  )

**Comment by eddybank** [comment]
Assign me please, I will get it sorted.

**Comment by arnab2001** [comment]
Great! I'm assigning you the issue

**Comment by deepbeatz** [comment]
this issue is already taken care of @arnab2001

**Comment by arnab2001** [comment]
@deepbeatz no , I had to revert it . Many things were broken and I think there's much better and clean way to make a sticky nav

**Comment by ManasaKaza** [comment]
I would like to work on this issue under JWOC
