### ISSUE TITLE
Add scroll back to top button in every page

### ISSUE THREAD

**Issue by zugzwang03** [arnab2001/Coinverse#76]
I want to add scroll back to top button in every page under JWOC'23.

**Comment by arnab2001** [comment]
you can no work on the issue

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by arnab2001** [comment]
@Awesomeasma i can assign you after you are done with your current issue

**Comment by zugzwang03** [comment]
Hey @arnab2001 , I was working on that issue. Why did you unassign me?

**Comment by arnab2001** [comment]
sorry  my bad, I didn't notice I assigned you 20hrs ago.
