### ISSUE TITLE
add testing with Cypress

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#8]

**Comment by sarkartanmay393** [comment]
Assign me

**Comment by arnab2001** [comment]
@sarkartanmay393 do you want to participate under jwoc ? if so then you need to write "I want to work on this issue under JWOC"

**Comment by sarkartanmay393** [comment]
I want to work on this issue under JWOC

**Comment by arnab2001** [comment]
@sarkartanmay393 assigned the issue to you , good luck 👍

**Comment by sarkartanmay393** [comment]
@arnab2001 Is there any private env data, you need to share with me?

**Comment by arnab2001** [comment]
Yes , there's .env file where you need to put api keys from rapid api 

Can drop me a text on coinverse discord channel in jwoc server . I can guide you better there

**Comment by arnab2001** [comment]
In sort , 
1.rename the .envDEMO to .env 
2. Go to rapid6api, search for coinranking api , subscribe to it (free tier) and copy the key from there and replace it in your .env

**Comment by sarkartanmay393** [comment]
@arnab2001 
### Raised PR: https://github.com/arnab2001/Coinverse/pull/39
