### ISSUE TITLE
[UI] Revamp Colors based on new logo

### ISSUE THREAD

**Issue by eddybank** [arnab2001/Coinverse#84]
Light Mode: 
![image](https://user-images.githubusercontent.com/89403905/223703636-7f1cdae6-e419-4650-b85c-aebb087e02ed.png)

Dark Mode:
![image](https://user-images.githubusercontent.com/89403905/223709928-2034df1c-7a49-4943-9edf-ab123ffe4263.png)

Assign myself and please provide some feedback on the the colors in the images.

**Comment by eddybank** [comment]
@arnab2001 

light-mode

![image](https://user-images.githubusercontent.com/89403905/224523591-e5932367-6cd3-4983-96e8-826ca30454b0.png)
![image](https://user-images.githubusercontent.com/89403905/224523596-eb674821-7371-4545-bead-b5872e6c576d.png)



Generated a color palette based off a few of the colors used already and a few with new logo colors and it came up with some blues close to what is used currently.

- --light-shades: rgb(249, 249, 249);
- --light-accent: rgb(152, 141, 152);
- --main-color: rgb(98, 107, 236);
- --dark-accent: rgb(53, 49, 56);
- --dark-shades: rgb(40, 54, 145);
- --darker-shades: rgb(32, 41, 102);

These colors are little brighter and still close to what is their currently and gives the addition of accent colors.

**Comment by eddybank** [comment]
@arnab2001 

https://user-images.githubusercontent.com/89403905/224530840-743df9b1-f5ba-468a-92e4-32156d00c589.mov

What do you think of this?

**Comment by arnab2001** [comment]
great work on the issue
