### ISSUE TITLE
Fix typos and improvements  in Readme.md

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#9]

**Comment by Sowham-3098** [comment]
I can work on this. And also add some other documentation.
1. code_of_conduct.md
2. LICENSE.md
3. contributors profile section in README.md

**Comment by arnab2001** [comment]
I assigned the issue to you, you can work on it

**Comment by Sowham-3098** [comment]
Please assign after the contribution period start.

**Comment by arnab2001** [comment]
Ok will do that

**Comment by Sowham-3098** [comment]
Assign this to me

**Comment by arnab2001** [comment]
assigned the issue with label , you can work on it now
