### ISSUE TITLE
Update readme.md with screenshot of site

### ISSUE THREAD

**Issue by arnab2001** [arnab2001/Coinverse#96]

**Comment by Awesomeasma** [comment]
I would like to work on this under JWOC

**Comment by arnab2001** [comment]
assigned you @Awesomeasma

**Comment by Awesomeasma** [comment]
@arnab2001 
I am having trouble running the application, the webpage is just visible for a second and then vanish, I could see errors in console. Would u mind to help me resolve this

**Comment by arnab2001** [comment]
You can use live version of the site : https://coinverse-delta.vercel.app/

For running it locally: 
1.Git clone 
2.Npm i 
3. Rename .envDEMO to .env
4. Go to rapidapi api site , subscribe to coinranking and Bing-news-search api 
5. Get the key from there and put it in your .env

**Comment by Awesomeasma** [comment]
> You can use live version of the site : https://coinverse-delta.vercel.app/
> 
> For running it locally: 1.Git clone 2.Npm i 3. Rename .envDEMO to .env 4. Go to rapidapi api site , subscribe to coinranking and Bing-news-search api 5. Get the key from there and put it in your .env

got it, thank you!
